version: '3'
services:
  frontend:
    image: nginx
    volumes:
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/proxy_params.conf:/etc/nginx/proxy_params
    ports:
      - "8080:80"
    links:
      - backend:backend
    restart: always

  backend:
    image: nginx
    volumes:
      - ./backend/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/var/www/html
